services:
  backend:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      MONGO_URI: ${MONGO_URI}

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: log-app

volumes:
  mongo-data: